import {
  Activity,
  AlertTriangle,
  Bell,
  Brain,
  Building2,
  Droplet,
  FileText,
  Flag,
  KeyRound,
  LayoutDashboard,
  Package,
  Settings,
  Ship,
  TestTube,
  Users,
} from 'lucide-react';
import type { SidebarItem } from '@bloodchain/ui/components';

export const navItems: SidebarItem[] = [
  { id: 'dashboard', label: 'Dashboard', labelKey: 'portal.nav.dashboard', icon: LayoutDashboard, href: '/' },
  { id: 'users', label: 'Users', labelKey: 'portal.nav.users', icon: Users, href: '/users' },
  { id: 'roles', label: 'Roles & Permissions', labelKey: 'portal.nav.roles', icon: KeyRound, href: '/roles' },
  { id: 'organizations', label: 'Organizations', labelKey: 'portal.nav.organizations', icon: Building2, href: '/organizations' },
  { id: 'couriers', label: 'Couriers', labelKey: 'portal.nav.couriers', icon: Ship, href: '/couriers' },
  { id: 'shipments', label: 'Shipments', labelKey: 'portal.nav.shipments', icon: Package, href: '/shipments' },
  { id: 'requests', label: 'Blood Requests', labelKey: 'portal.nav.requests', icon: Droplet, href: '/requests' },
  { id: 'emergencies', label: 'Emergencies', labelKey: 'portal.nav.emergencies', icon: AlertTriangle, href: '/emergencies' },
  { id: 'moderation', label: 'Content Moderation', labelKey: 'portal.nav.moderation', icon: Flag, href: '/moderation' },
  { id: 'inventory', label: 'Inventory', labelKey: 'portal.nav.inventory', icon: TestTube, href: '/inventory' },
  { id: 'alerts', label: 'Alerts', labelKey: 'portal.nav.alerts', icon: Bell, href: '/alerts' },
  { id: 'ai-analytics', label: 'AI Analytics', labelKey: 'portal.nav.aiAnalytics', icon: Brain, href: '/ai-analytics' },
  { id: 'audit', label: 'Audit Logs', labelKey: 'portal.nav.audit', icon: FileText, href: '/audit' },
  { id: 'health', label: 'System Health', labelKey: 'portal.nav.health', icon: Activity, href: '/health' },
  { id: 'settings', label: 'Settings', labelKey: 'portal.nav.settings', icon: Settings, href: '/settings' },
];
