export const XP_CONFIG = {
  DONATION_COMPLETED: 50,
  EMERGENCY_DONATION_COMPLETED: 75,
  BLOOD_TEST_COMPLETED: 20,
  APPOINTMENT_COMPLETED: 15,
  PROFILE_COMPLETED: 25,
  ACHIEVEMENT_UNLOCKED: 10,
  EMERGENCY_RESPONSE_ACCEPTED: 25,
  STREAK_BONUS: 5,
} as const;

export const LEVEL_CONFIG = {
  MAX_LEVEL: 10,
  XP_THRESHOLDS: [
    0,      // Level 1
    100,    // Level 2
    250,    // Level 3
    500,    // Level 4
    1000,   // Level 5
    2000,   // Level 6
    3500,   // Level 7
    5500,   // Level 8
    8000,   // Level 9
    11000,  // Level 10
  ] as const,
} as const;

export const LEVEL_NAMES: Record<number, string> = {
  1: 'New Donor',
  2: 'Active Donor',
  3: 'Regular Donor',
  4: 'Community Donor',
  5: 'Dedicated Donor',
  6: 'Champion',
  7: 'Elite Donor',
  8: 'Hero',
  9: 'Legend',
  10: 'Platinum',
};

export const ACHIEVEMENT_DEFINITIONS = [
  {
    code: 'FIRST_DONATION',
    type: 'DONATION_COUNT' as const,
    name: 'First Donation',
    description: 'Complete your first blood donation',
    icon: 'droplet',
    rarity: 'COMMON' as const,
    criteria: { type: 'DONATION_COUNT', target: 1 },
    xpReward: 25,
    displayOrder: 1,
  },
  {
    code: 'FIFTH_DONATION',
    type: 'DONATION_COUNT' as const,
    name: 'Five Times a Hero',
    description: 'Complete 5 blood donations',
    icon: 'droplet-plus',
    rarity: 'RARE' as const,
    criteria: { type: 'DONATION_COUNT', target: 5 },
    xpReward: 50,
    displayOrder: 2,
  },
  {
    code: 'TENTH_DONATION',
    type: 'DONATION_COUNT' as const,
    name: 'Decade of Dedication',
    description: 'Complete 10 blood donations',
    icon: 'award',
    rarity: 'EPIC' as const,
    criteria: { type: 'DONATION_COUNT', target: 10 },
    xpReward: 100,
    displayOrder: 3,
  },
  {
    code: 'TWENTIETH_DONATION',
    type: 'DONATION_COUNT' as const,
    name: 'Lifeline',
    description: 'Complete 20 blood donations',
    icon: 'heart',
    rarity: 'LEGENDARY' as const,
    criteria: { type: 'DONATION_COUNT', target: 20 },
    xpReward: 200,
    displayOrder: 4,
  },
  {
    code: 'EMERGENCY_RESPONDER',
    type: 'EMERGENCY_RESPONSE_COUNT' as const,
    name: 'Emergency Responder',
    description: 'Successfully respond to an emergency blood request',
    icon: 'alert-circle',
    rarity: 'RARE' as const,
    criteria: { type: 'EMERGENCY_RESPONSE_COUNT', target: 1 },
    xpReward: 75,
    displayOrder: 5,
  },
  {
    code: 'COMMUNITY_BUILDER',
    type: 'EMERGENCY_RESPONSE_COUNT' as const,
    name: 'Community Builder',
    description: 'Respond to 5 emergency blood requests',
    icon: 'users',
    rarity: 'EPIC' as const,
    criteria: { type: 'EMERGENCY_RESPONSE_COUNT', target: 5 },
    xpReward: 150,
    displayOrder: 6,
  },
  {
    code: 'FIRST_BLOOD_TEST',
    type: 'BLOOD_TEST_COUNT' as const,
    name: 'Health Explorer',
    description: 'Complete your first blood test',
    icon: 'activity',
    rarity: 'COMMON' as const,
    criteria: { type: 'BLOOD_TEST_COUNT', target: 1 },
    xpReward: 20,
    displayOrder: 7,
  },
  {
    code: 'FIVE_BLOOD_TESTS',
    type: 'BLOOD_TEST_COUNT' as const,
    name: 'Wellness Champion',
    description: 'Complete 5 blood tests',
    icon: 'trending-up',
    rarity: 'RARE' as const,
    criteria: { type: 'BLOOD_TEST_COUNT', target: 5 },
    xpReward: 40,
    displayOrder: 8,
  },
  {
    code: 'PROFILE_COMPLETE',
    type: 'PROFILE_COMPLETED' as const,
    name: 'Getting Started',
    description: 'Complete your donor profile',
    icon: 'user-check',
    rarity: 'COMMON' as const,
    criteria: { type: 'PROFILE_COMPLETED', target: 1 },
    xpReward: 25,
    displayOrder: 9,
  },
  {
    code: 'XP_MILESTONE_500',
    type: 'XP_MILESTONE' as const,
    name: 'Rising Star',
    description: 'Earn 500 XP',
    icon: 'star',
    rarity: 'RARE' as const,
    criteria: { type: 'XP_MILESTONE', target: 500 },
    xpReward: 50,
    displayOrder: 10,
  },
  {
    code: 'XP_MILESTONE_2000',
    type: 'XP_MILESTONE' as const,
    name: 'Superstar',
    description: 'Earn 2000 XP',
    icon: 'star',
    rarity: 'EPIC' as const,
    criteria: { type: 'XP_MILESTONE', target: 2000 },
    xpReward: 100,
    displayOrder: 11,
  },
  {
    code: 'XP_MILESTONE_5000',
    type: 'XP_MILESTONE' as const,
    name: 'Legendary Hero',
    description: 'Earn 5000 XP',
    icon: 'zap',
    rarity: 'LEGENDARY' as const,
    criteria: { type: 'XP_MILESTONE', target: 5000 },
    xpReward: 200,
    displayOrder: 12,
  },
  {
    code: 'CONSISTENT_DONOR',
    type: 'STREAK' as const,
    name: 'Consistent Donor',
    description: 'Donate blood twice within 6 months',
    icon: 'calendar-check',
    rarity: 'RARE' as const,
    criteria: { type: 'STREAK', target: 2, timeframeMonths: 6 },
    xpReward: 60,
    displayOrder: 13,
  },
] as const;

export const BADGE_DEFINITIONS = [
  {
    code: 'FIRST_DONATION_BADGE',
    name: 'First Drop',
    description: 'Awarded for your first donation',
    icon: 'droplet',
    rarity: 'COMMON' as const,
    achievementCode: 'FIRST_DONATION',
    displayOrder: 1,
  },
  {
    code: 'HERO_BADGE',
    name: 'Hero',
    description: 'Awarded for 10 donations',
    icon: 'award',
    rarity: 'EPIC' as const,
    achievementCode: 'TENTH_DONATION',
    displayOrder: 2,
  },
  {
    code: 'LIFELINE_BADGE',
    name: 'Lifeline',
    description: 'Awarded for 20 donations',
    icon: 'heart',
    rarity: 'LEGENDARY' as const,
    achievementCode: 'TWENTIETH_DONATION',
    displayOrder: 3,
  },
  {
    code: 'EMERGENCY_RESPONDER_BADGE',
    name: 'Emergency Hero',
    description: 'Awarded for emergency response',
    icon: 'alert-circle',
    rarity: 'RARE' as const,
    achievementCode: 'EMERGENCY_RESPONDER',
    displayOrder: 4,
  },
  {
    code: 'HEALTH_CHAMPION_BADGE',
    name: 'Health Champion',
    description: 'Awarded for regular health checks',
    icon: 'activity',
    rarity: 'COMMON' as const,
    achievementCode: 'FIRST_BLOOD_TEST',
    displayOrder: 5,
  },
  {
    code: 'RISING_STAR_BADGE',
    name: 'Rising Star',
    description: 'Awarded for earning 500 XP',
    icon: 'star',
    rarity: 'RARE' as const,
    achievementCode: 'XP_MILESTONE_500',
    displayOrder: 6,
  },
  {
    code: 'PLATINUM_BADGE',
    name: 'Platinum',
    description: 'Awarded for reaching maximum level',
    icon: 'shield',
    rarity: 'LEGENDARY' as const,
    achievementCode: null,
    displayOrder: 7,
  },
] as const;
