/**
 * Regenerates docs/clinical-review.md from the catalogues.
 *
 * Derived, never hand-typed: a term added to the `medical` namespace has to
 * appear on the review list without anyone remembering to add it, which is the
 * same reason CLINICAL_REVIEW_KEYS is computed rather than listed. Run
 * `pnpm clinical:review` after touching anything under `medical`; the spec in
 * packages/i18n fails if the file and the catalogue disagree.
 *
 * Reviewer decisions live in the Status and Notes columns and are preserved
 * across regenerations, so a clinician's sign-off is not lost when a new term
 * is added below it.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'docs', 'clinical-review.md');

/** The locale files are plain object literals; strip the TS and import them. */
async function catalogue(locale) {
  const src = readFileSync(join(ROOT, 'packages/i18n/src/locales', `${locale}.ts`), 'utf8')
    .replace(/^import type[\s\S]*?;\n/m, '')
    .replace(/export const \w+: Catalog =/, 'export default');
  const url = `data:text/javascript;charset=utf-8;base64,${Buffer.from(src, 'utf8').toString('base64')}`;
  return (await import(url)).default;
}

function flatten(node, prefix = '') {
  const out = {};
  for (const [key, value] of Object.entries(node)) {
    const path = prefix ? `${prefix}.${key}` : key;
    if (typeof value === 'string') out[path] = value;
    else Object.assign(out, flatten(value, path));
  }
  return out;
}

/** Reviewer columns from the existing file, keyed by translation key. */
function existingDecisions() {
  if (!existsSync(OUT)) return {};
  const decisions = {};
  for (const line of readFileSync(OUT, 'utf8').split('\n')) {
    // Split on unescaped pipes only: a translation may legitimately contain
    // one, and `cell()` writes it as `\\|`.
    const cells = line.split(/(?<!\\)\|/).map((text) => text.trim());
    // A row is: '' | key | en | uz | ru | status | notes | ''
    if (cells.length !== 8 || !cells[1]?.startsWith('`medical.')) continue;
    decisions[cells[1].replace(/`/g, '')] = { status: cells[5] ?? '', notes: cells[6] ?? '' };
  }
  return decisions;
}

/** A cell that cannot break the table or be mistaken for markup. */
const cell = (text) => text.replace(/\|/g, '\\|').replace(/\n/g, ' ');

const [en, uz, ru] = await Promise.all([catalogue('en'), catalogue('uz'), catalogue('ru')]);
const [fen, fuz, fru] = [flatten(en), flatten(uz), flatten(ru)];
const keys = Object.keys(fen).filter((key) => key.startsWith('medical.')).sort();
const kept = existingDecisions();

const rows = keys.map((key) => {
  const prior = kept[key];
  const status = prior?.status || 'PENDING';
  const notes = prior?.notes || '';
  return `| \`${key}\` | ${cell(fen[key])} | ${cell(fuz[key] ?? '—')} | ${cell(fru[key] ?? '—')} | ${status} | ${notes} |`;
});

const pending = rows.filter((row) => row.includes('| PENDING |')).length;

const body = `# Clinical review manifest

Every clinically meaningful string in the product, in all three languages, for a
clinician to confirm before release.

**${keys.length} terms — ${pending} pending, ${keys.length - pending} approved.**

## How to read this

The \`medical\` namespace exists so that everything a donor could act on
medically — what they are donating, whether they may donate, what a laboratory
value means — sits in one place instead of being spread across nine screens.
This file is that namespace, rendered. It is generated from the catalogues by
\`pnpm clinical:review\`, so a term added to \`medical\` appears here whether or
not anyone remembers to add it.

The Uzbek and Russian wording is **deliberately literal**. It was written to be
confirmed or replaced by a clinician, not improved by a translator — a
plausible-sounding translation of a laboratory flag is more dangerous than an
awkward one, because nobody re-reads it.

## How to review

1. Read the English source. If the English itself is wrong or misleading, say so
   in Notes — that is the more important finding.
2. Check the Uzbek and Russian say the same clinical thing, not merely a
   similar-sounding thing.
3. Set Status to \`APPROVED\` or \`CHANGE REQUESTED\`, and put the replacement
   wording in Notes.
4. Re-running \`pnpm clinical:review\` preserves both columns, so sign-off is
   not lost when a new term is added.

Nothing here should be edited in the catalogue without a reviewer's decision
recorded in this file.

## Terms

| Translation key | English source | Uzbek (Latin) | Russian | Status | Reviewer notes |
| --- | --- | --- | --- | --- | --- |
${rows.join('\n')}

---

_Generated by \`pnpm clinical:review\` from \`packages/i18n/src/locales\`. Do not
edit the first four columns by hand — edit the catalogue and regenerate._
`;

writeFileSync(OUT, body);
console.log(`docs/clinical-review.md: ${keys.length} terms, ${pending} pending`);
